version: "3.8"
services:

    # PHP service
    app:
        image: satellite
        container_name: php-app
        stdin_open: true
        tty: true
        depends_on:
            - db
        ports:
            - "8000:8000"
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network
        volumes:
            - ./data:/var/lib/mysql

networks:
    app-network:
        driver: bridge

volumes:
    data:
