version: "3.8"
services:

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql_db
        hostname: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        env_file:
            - ./.env
        networks:
            - dockerlan
        volumes:
            - ./data:/var/lib/mysql

    # PHP service
    app:
        image: satellite
        container_name: php-app
        stdin_open: true
        tty: true
        depends_on:
            - db
        ports:
            - "8000:8000"
        networks:
            - dockerlan
        entrypoint: ./entrypoint.sh

networks:
    dockerlan:

volumes:
    data:
